sources:
  - haskoy.glyphs
#buildVariable: false
axisOrder:
      - wght
familyName: Haskoy
stat:
      haskoy[wght].ttf:
      - name: Weight
        tag: wght
        values:
        - name: Thin
          value: 100
        - name: ExtraLight
          value: 200
        - name: Light
          value: 300
        - name: Regular
          value: 400
        - name: Medium
          value: 500
        - name: SemiBold
          value: 600
        - name: Bold
          value: 700
        - name: ExtraBold
          value: 800